name: social_cv_api
description: A social CV API
version: 0.0.1
author: Axel LE BOT <axellebot@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.2.1

dev_dependencies:
  test: ^1.3.0
  aqueduct_test: ^1.0.1
