name: social_cv_api
description: A social CV API
publish_to: none # Ensure we don't accidentally publish our private code! ;)
version: 0.0.1
author: Axel LE BOT <axellebot@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  # Angel
  angel_migration_runner: ^2.0.0-alpha
  angel_oauth2: ^2.3.0 # Supports stateless authentication via OAuth 2.0
  angel_configuration: ^2.1.0 # Loads application configuration, along with support for .env files.
  angel_framework: ^2.0.4+1 # The core server library.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_migration: ^2.0.0 # Migration runtime support
  angel_orm: ^2.0.1 # Migration runtime support
  angel_orm_postgres: ^1.0.0 # PostgreSQL support for Angel ORM
  angel_serialize: ^2.2.3 # Serialization runtime support
  angel_production: ^1.0.0 # Production application runner.
  angel_static: ^2.1.3 # Static file server
  angel_validate: ^2.0.1 # Allows for validation of input data

  # Others
  meta: ^1.1.7
  dbcrypt: ^1.0.0
  uuid: ^2.0.2
  json_annotation: ^2.4.0

dev_dependencies:
  # Angel
  angel_hot: ^2.0.6 # Hot-reloading support. :)
  angel_migration_runner: ^2.0.0 # Runs migrations
  angel_orm_generator: ^2.0.5 # Generates ORM libraries
  angel_serialize_generator: ^2.5.0 # Generates model serialization code
  angel_test: ^2.0.1 # Utilities for testing Angel servers.

  # Others
  build_runner: ^1.0.0 # Runs builds
  json_serializable: ^3.0.0 # Json serialization
  io: ^0.3.2 # For pretty printing.
  pedantic: ^1.0.0 # Enforces Dart style conventions.
  test: ^1.3.0 # For unit testing.
